### ISSUE TITLE
Connect Sign In UI

### ISSUE THREAD

**Issue by LukePulverenti** [MediaBrowser/MediaBrowser.WindowsRT#67]
I would consider going with the vertical design used by other apps (see the new iOS screens), because right now without reading it's not obvious they belong together.

That's going to allow you to reduce the amount of text displayed if you update to match iOS. (I will update iOS to include the signup link for connect).

Also I would make the text fields a little longer, and have the buttons use the same width as the inputs. 

I personally would also consider a visual style for the buttons to make them more distinct (like the solid green in iOS)...but if this goes terribly against Win8 conventions then no big deal.

**Comment by 7illusions** [comment]
Done in v3.2.0
