### ISSUE TITLE
Get QualityOptions from DialogOptions

### ISSUE THREAD

**Issue by LukePulverenti** [MediaBrowser/MediaBrowser.WindowsRT#70]
The list of quality options to present are now dynamic and contained in the DialogOptions object. Each QualityOption has a name and id. Use the id when saving into the object.

As a result, you'll probably need to get rid of your sync settings page where the user can pick the default. (Perhaps just remember previous instead).

**Comment by 7illusions** [comment]
Implemented in v3.2.0
